# Site settings
title: AK
email: arjun.kholia1234@gmail.com
description: > # This is a blog dedicated to my Data Scence projects completed on Python.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "ArjunKholia.github.io" # the base hostname & protocol for your site
facebook_username: arjun.kholia1234
github_username:  ArjunKholia
linkedin_username:    ArjunKholia


# Build settings
markdown: kramdown
